### ISSUE TITLE
Rewards paid history is not being updated with proper amount

### ISSUE THREAD

**Issue by sgdias** [dakk/lisk-pool3#14] opened 2021-08-29 21:15 UTC
steps to reproduce:

1) execute python3 liskpool3.py --only-update
3) execute update_frontend.sh and browse to stats page
4) execute python3 liskpool3.py
5) execute bash payments.sh
6) execute update_frontend.sh and browse to stats page

The latest paid amount result to be the same as previous in history

**Comment by dakk** [comment] 2021-08-29 21:26
also: 

> pending reward is updating fine, but now latest paid reward in history is not

**Comment by dakk** [comment] 2021-08-30 13:27
@sgdias can you provide me your poollogs at first and second step?

**Comment by sgdias** [comment] 2021-08-30 15:38
I'll try to reproduce later when back to home and provide.

**Comment by sgdias** [comment] 2021-08-31 16:25
I kept running a script for periodical only updates and after some time I executed a update with payment, the rewards field at history remained 0 despite it was paid. I'm attaching the script a the collected multiple outputs of poollogs.json
[logAndScripts.zip](https://github.com/dakk/lisk-pool3/files/7085412/logAndScripts.zip)

**Comment by dakk** [comment] 2021-09-01 07:03
Ok, if the problem is only the "rewards" field in history, it should be fixed. Please try latest version

**Closed** 2021-09-01 07:02 UTC
Labels: bug, help wanted

**Comment by sgdias** [comment] 2021-09-01 18:28
awesome, I'll update to latest. Thanks.
